# Generated by Django 5.2.16 on 2026-07-11 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billing_connection_fee_billing_reconnection_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='penalty_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
