# Generated by Django 5.2.16 on 2026-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billing_penalty_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='current_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
