# Generated by Django 5.2.16 on 2026-07-13 03:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_billing_current_reading'),
        ('customer', '0009_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('general', 'General'), ('reconnection', 'Reconnection'), ('disconnection', 'Disconnection'), ('clearing_operation', 'Clearing Operation'), ('maintenance', 'Maintenance'), ('billing', 'Billing'), ('payment_reminder', 'Payment Reminder'), ('others', 'Others')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_expiry)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
