# Generated by Django 5.2.16 on 2026-07-13 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
        ('customer', '0009_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('customer', 'Single Customer'), ('barangay', 'Barangay'), ('all', 'All Customers')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('general', 'General'), ('billing', 'Billing'), ('payment_reminder', 'Payment Reminder'), ('disconnection', 'Disconnection'), ('reconnection', 'Reconnection'), ('maintenance', 'Maintenance'), ('clearing_operation', 'Clearing Operation')], default='general', max_length=30),
        ),
    ]
