# Generated by Django 5.2.16 on 2026-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
