# Generated by Django 5.2.16 on 2026-07-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='submitter_no',
            field=models.CharField(default=14.069444444444445, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
