# Generated by Django 5.2.16 on 2026-07-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=14.069444444444445, max_length=250),
            preserve_default=False,
        ),
    ]
