# Generated by Django 5.2.16 on 2026-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'New Applicant'), ('old', 'Old Customer')], default='new', max_length=20),
        ),
    ]
