# Generated by Django 5.2.16 on 2026-07-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=100, unique=True)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'ordering': ['barangay_name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default=14.069444444444445, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='middlename',
            field=models.CharField(default=14.069444444444445, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='barangay',
            field=models.ForeignKey(default=14.069444444444445, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customer.barangay'),
            preserve_default=False,
        ),
    ]
