# Generated by Django 5.2.16 on 2026-07-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_barangay_customer_lastname_customer_middlename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullname',
            new_name='firstname',
        ),
    ]
