# Generated by Django 5.2.16 on 2026-07-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_fullname_customer_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='submitter_no',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
